services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runtime
    volumes:
      - ./backend:/app/backend
      - ./frontend/build:/app/backend/public           # Map built frontend assets to Express public folder
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    networks:
      - private_net
    profiles:
      - dev
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: build
    volumes:
      - ./frontend:/app/frontend                      # Map frontend source for live rebuilds
      - ./frontend/build:/app/frontend/build          # Ensure frontend builds are accessible to backend
    command: ["npm", "run", "build", "--", "--watch"] # Watch for changes and rebuild
    networks:
      - private_net
    profiles:
      - dev

networks:
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.63.0.0/16

